### ISSUE TITLE
error quando é usado o import

### ISSUE THREAD

**Issue by Marzeu** [davibaltar/example-swagger-autogen-with-router#1]
Olá amigo, tudo bem?

Quando estou usando o autogen com import ao invés do require ele dispara um erro de que não é capaz de encontrar o modulo.

o app.js está assim:

import express from 'express';
import routes from './routes';
import './database';

class App {
    constructor() {
        this.server = express();
        this.middleware();
        this.routes();
    }

    middleware() {
        this.server.use(express.json());        
    }

    routes() {
        this.server.use(routes);
    }
}

export default new App().server;

o routes está assim:

import { Router } from 'express';
import swaggerUi from 'swagger-ui-express';
import swaggerFile from '../swagger_output.json';
import SessionController from './app/controllers/SessionController';
import AuthMiddleware from './app/middlewares/auth';
import UserController from './app/controllers/userController';

const routes = new Router();

routes.use('/api/docs', swaggerUi.serve);
routes.get('/api/docs', swaggerUi.setup(swaggerFile));

routes.get('/api', (req, res) => {
    res.status(200).send({
        success: "true",
        title: 'Seja bem-vindo(a) no GigAPI + Node.js + PostgreSQL!',
        version: '1.0.0'
    });
});

routes.get('/users', UserController.show);
routes.post('/users', UserController.store);

routes.post('/sessions', SessionController.store);
routes.put('/users/:id', AuthMiddleware, UserController.update);

export default routes;

o erro é disparado quando a função é chamado para usar o autogen no arquivo swagger.js

 swaggerAutogen(options)(outputFile, endpointsFiles, doc).then(async () => {
    await import('./src/app.js').catch(error => {
        console.error("deu ruim", error.message);
    });
});

você teria ideia de como resolver?

**Comment by davibaltar** [comment]
Olá @Marzeu. Tudo joia!  Você adicionou o atributo `"type": "module"` no seu arquivo package.json?

Por exemplo:

```js
{
    "name": "...",
    "version": "...",
    "type": "module",
    ...
}
```

Caso já tenha feito isso, posta o erro aqui, por favor.

**Comment by ncesar** [comment]
@davibaltar Aqui, mesmo utilizando o type module, se o arquivo for .ts, ele da esse ero: 
![image](https://user-images.githubusercontent.com/29064514/178371764-bcd35f68-4a04-4b39-94a5-768da9d7675c.png)

**Comment by davibaltar** [comment]
Olá @ncesar! Desculpa a demora. A versão 2.22.0 fez correções sobre isso e adicionou o arquivo .d.ts e tsconfig.json na lib.

Segue um exemplo (mas atualize a versão do exemplo para a 2.22.0): https://github.com/marcelino-borges/swagger-autogen-test

Caso não funcione, me avisem que eu abro novamente a issue.
